Azure/terraform-azurerm-avm-res-azurestackhci-cluster

README.md
_header.md
deploy.tf
examples/default/README.md
examples/default/main.tf
keyvault.tf
locals.tf
main.tf
outputs.tf
rolebindings.tf
storageaccount.tf
validate.tf
variables.tf

Support more variables

---

README.md
keyvault.tf
variables.tf

remove key_vault_name

---

README.md
locals.tf
storageaccount.tf
validate.tf
variables.tf

Add storageAdapterIPInfo and operation_type, remove storage account id

---

validate.tf

Fix: storage account name

---

README.md
locals.tf
validate.tf
variables.tf

add a new paramter to set storageAdapterIPInfo

---

README.md
locals.tf
variables.tf

fix the storage adapter ip info type

---

locals.tf
validate.tf
variables.tf

add null support for operation_type

---

variables.tf

fix validation logic for operation_type

---

README.md
deploy.tf
locals.tf
main.tf
validate.tf
variables.tf

Add more options to override the default values

---

deploy.tf
main.tf
validate.tf

revert namespace casing

---

README.md
keyvault.tf
locals.tf
variables.tf

add keyvault_secrets to define secrets sequence and suffixes

---

README.md
keyvault.tf
variables.tf

add variables to set expiration date for secrets

---

README.md
examples/default/README.md
examples/default/main.tf
keyvault.tf
locals.tf
main.tf
rolebindings.tf
storageaccount.tf
validate.tf
variables.tf

Use resource group id & handle no witness storage account

---

README.md
keyvault.tf
locals.tf
storageaccount.tf
variables.tf

resource_group_location default empty

---

keyvault.tf

use witness_type to control whether create witness_storage_key

---

rolebindings.tf
terraform.tf

user lowercase key vault name for role binding scopes

---

README.md
keyvault.tf
variables.tf

Add new variables 'tenant_id'

---

README.md
locals.tf
variables.tf

add more options to override network settings

---

README.md
locals.tf
variables.tf

add switch on whether to create role assignments for hci rp

---

examples/default/README.md
examples/default/main.tf

Update readme: prerequisite for permission
